# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/mob_accept.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mob_acc(object):
    def setupUi(self, mob_acc):
        mob_acc.setObjectName("mob_acc")
        mob_acc.resize(430, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./UI/../Ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mob_acc.setWindowIcon(icon)
        mob_acc.setStyleSheet("background: #121212;\n"
"color: #ffffff")
        self.abort = QtWidgets.QPushButton(mob_acc)
        self.abort.setGeometry(QtCore.QRect(10, 560, 191, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.abort.setFont(font)
        self.abort.setStyleSheet("color: #ffffff;\n"
"background: #414141;\n"
"border-radius: 5px")
        self.abort.setObjectName("abort")
        self.save = QtWidgets.QPushButton(mob_acc)
        self.save.setGeometry(QtCore.QRect(230, 560, 191, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.save.setFont(font)
        self.save.setStyleSheet("color: #ffffff;\n"
"background: #414141;\n"
"border-radius: 5px")
        self.save.setObjectName("save")
        self.headline = QtWidgets.QLabel(mob_acc)
        self.headline.setGeometry(QtCore.QRect(10, 10, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.headline.setFont(font)
        self.headline.setStyleSheet("color: #ffffff")
        self.headline.setObjectName("headline")
        self.label = QtWidgets.QLabel(mob_acc)
        self.label.setGeometry(QtCore.QRect(10, 50, 411, 491))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #ffffff")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")

        self.retranslateUi(mob_acc)
        QtCore.QMetaObject.connectSlotsByName(mob_acc)

    def retranslateUi(self, mob_acc):
        _translate = QtCore.QCoreApplication.translate
        mob_acc.setWindowTitle(_translate("mob_acc", "Form"))
        self.abort.setText(_translate("mob_acc", "Отмена"))
        self.save.setText(_translate("mob_acc", "Сохранить"))
        self.headline.setText(_translate("mob_acc", "Будет создан:"))
