# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/Main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Designer(object):
    def setupUi(self, Designer):
        Designer.setObjectName("Designer")
        Designer.setWindowModality(QtCore.Qt.NonModal)
        Designer.resize(400, 377)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./UI/../Ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Designer.setWindowIcon(icon)
        Designer.setLayoutDirection(QtCore.Qt.LeftToRight)
        Designer.setAutoFillBackground(False)
        Designer.setStyleSheet("background: #121212;\n"
"\n"
"\n"
"QPushButton#pushButton {\n"
"    color: #ffffff;\n"
"    background: #414141;\n"
"    border-radius: 5px;\n"
"    height: 25px\n"
"}\n"
"\n"
"QPushButton#pushButton::hover {\n"
"    background-color: rgb(224, 255, 0);\n"
"}\n"
"\n"
"QPushButton#pushButton::pressed {\n"
"    background-color: rgb(224, 0, 0);     \n"
"}")
        Designer.setDocumentMode(False)
        Designer.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(Designer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #ffffff")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #ffffff")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.help = QtWidgets.QPushButton(self.centralwidget)
        self.help.setStyleSheet("QPushButton {\n"
"    color: #ffffff;\n"
"    background: #414141;\n"
"    border-radius: 5px;\n"
"    height: 25px\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color:rgb(0, 255, 0);     \n"
"}")
        self.help.setObjectName("help")
        self.verticalLayout.addWidget(self.help)
        self.New_mob = QtWidgets.QPushButton(self.centralwidget)
        self.New_mob.setEnabled(True)
        self.New_mob.setStyleSheet("QPushButton {\n"
"    color: #ffffff;\n"
"    background: #414141;\n"
"    border-radius: 5px;\n"
"    height: 25px\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color:rgb(0, 255, 0);     \n"
"}")
        self.New_mob.setObjectName("New_mob")
        self.verticalLayout.addWidget(self.New_mob)
        self.custom_item = QtWidgets.QPushButton(self.centralwidget)
        self.custom_item.setStyleSheet("QPushButton {\n"
"    color: #ffffff;\n"
"    background: #414141;\n"
"    border-radius: 5px;\n"
"    height: 25px\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color:rgb(0, 255, 0);     \n"
"}")
        self.custom_item.setObjectName("custom_item")
        self.verticalLayout.addWidget(self.custom_item)
        self.c_item_table = QtWidgets.QPushButton(self.centralwidget)
        self.c_item_table.setStyleSheet("QPushButton {\n"
"    color: #ffffff;\n"
"    background: #414141;\n"
"    border-radius: 5px;\n"
"    height: 25px\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color:rgb(0, 255, 0);     \n"
"}")
        self.c_item_table.setObjectName("c_item_table")
        self.verticalLayout.addWidget(self.c_item_table)
        self.Open_file = QtWidgets.QPushButton(self.centralwidget)
        self.Open_file.setStyleSheet("QPushButton {\n"
"    color: #ffffff;\n"
"    background: #414141;\n"
"    border-radius: 5px;\n"
"    height: 25px\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color:rgb(0, 255, 0);     \n"
"}")
        self.Open_file.setObjectName("Open_file")
        self.verticalLayout.addWidget(self.Open_file)
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setStyleSheet("QPushButton {\n"
"    color: #ffffff;\n"
"    background: rgb(85, 0, 0);\n"
"    border-radius: 5px;\n"
"    height: 25px\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: rgb(170, 0, 0);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgb(224, 0, 0);     \n"
"}")
        self.exit.setObjectName("exit")
        self.verticalLayout.addWidget(self.exit)
        Designer.setCentralWidget(self.centralwidget)

        self.retranslateUi(Designer)
        QtCore.QMetaObject.connectSlotsByName(Designer)

    def retranslateUi(self, Designer):
        _translate = QtCore.QCoreApplication.translate
        Designer.setWindowTitle(_translate("Designer", "MMCreator"))
        self.label.setText(_translate("Designer", "\n"
"MythicMobs\n"
"Creator\n"
""))
        self.label_2.setText(_translate("Designer", "error 404"))
        self.help.setText(_translate("Designer", "Помощь"))
        self.New_mob.setText(_translate("Designer", " Lite Новый моб"))
        self.custom_item.setText(_translate("Designer", "Lite Кастомный предмет"))
        self.c_item_table.setText(_translate("Designer", "WIP Таблица предметов"))
        self.Open_file.setText(_translate("Designer", " WIP Открыть файл"))
        self.exit.setText(_translate("Designer", "Выйти"))
